// auth
export const AUTH_ACTION_START = 'AUTH_ACTION_START';
export const AUTH_ACTION_FAIL = 'AUTH_ACTION_FAIL';

// cart
export const CART_ACTION_START = 'CART_ACTION_START';
export const CART_ACTION_FAIL = 'CART_ACTION_FAIL';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREASE_PRODUCT_COUNT_OF_CART = 'INCREASE_PRODUCT_COUNT_OF_CART';
export const DECREASE_PRODUCT_COUNT_OF_CART = 'DECREASE_PRODUCT_COUNT_OF_CART';


// category
export const CATEGORY_ACTION_START = 'CATEGORY_ACTION_START';
export const CATEGORY_ACTION_FAIL = 'CATEGORY_ACTION_FAIL';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

// filter
// category filters
export const SET_CATEGORY_TEXT_FILTER = 'SET_CATEGORY_TEXT_FILTER';
export const SET_SUBCATEGORY_TEXT_FILTER = 'SET_SUBCATEGORY_TEXT_FILTER';
export const SET_PRODUCT_TEXT_FILTER = 'SET_PRODUCT_TEXT_FILTER';
export const SET_USER_TEXT_FILTER = 'SET_USER_TEXT_FILTER';

export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';

export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SET_SORT_BY_CATEGORY_TITLE = 'SET_SORT_BY_CATEGORY_TITLE';
export const SET_SORT_BY_SUBCATEGORY_TITLE = 'SET_SORT_BY_SUBCATEGORY_TITLE';
export const SET_SORT_BY_PRODUCT_TITLE = 'SET_SORT_BY_PRODUCT_TITLE';
export const SET_SORT_BY_USER_TITLE = 'SET_SORT_BY_USER_TITLE';
export const SET_SORT_BY_PRODUCT_PRICE = 'SET_SORT_BY_PRODUCT_PRICE';


export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const SET_SUBCATEGORY_ID = 'SET_SUBCATEGORY_ID';
export const SET_SELLER_ID = 'SET_SELLER_ID';


// product filters
export const SET_LOW_PRICE = 'SET_LOW_PRICE';
export const SET_HIGH_PRICE = 'SET_HIGH_PRICE';
export const UNSET_PRICE = 'UNSET_PRICE';
export const ADD_RATING_COUNT = 'ADD_RATING_COUNT';
export const REMOVE_RATING_COUNT = 'REMOVE_RATING_COUNT';
export const UNSET_RATING = 'UNSET_RATING';


// user filters
export const SET_EMAIL_TEXT_FILTER = 'SET_EMAIL_TEXT_FILTER';
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER';
export const SET_CONTACT_NUMBER_TEXT_FILTER = 'SET_CONTACT_NUMBER_TEXT_FILTER';
export const SET_PIN_CODE_TEXT_FILTER = 'SET_PIN_CODE_TEXT_FILTER';
export const SET_STATE_TEXT_FILTER = 'SET_STATE_TEXT_FILTER';

// order
export const PLACE_ORDER = 'PLACE_ORDER';


// product
export const PRODUCT_ACTION_START = 'PRODUCT_ACTION_START';
export const PRODUCT_ACTION_FAIL = 'PRODUCT_ACTION_FAIL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const RATE_PRODUCT = 'RATE_PRODUCT';
export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT';

// subcategory
export const SUBCATEGORY_ACTION_START = 'SUBCATEGORY_ACTION_START';
export const SUBCATEGORY_ACTION_FAIL = 'SUBCATEGORY_ACTION_FAIL';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const REMOVE_SUBCATEGORY = 'REMOVE_SUBCATEGORY';

// user
export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAIL = 'USER_ACTION_FAIL';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';
export const REMOVE_USER_ADDRESS = 'REMOVE_USER_ADDRESS';
